services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mern-admin:
    build: .
    container_name: mern-admin
    restart: always
    ports:
      - "8192:8192"
    environment:
      # These will be overridden by GitHub Actions workflow inline variables
      DATABASE: mongodb://mongo:27017/mydb
      SECRET: mySuperSecret
      KEY: mySessionKey
    depends_on:
      - mongo

volumes:
  mongo-data:
