version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mern-admin:
    build: .
    container_name: mern-admin
    restart: always
    ports:
      - "8192:8192"
    env_file:
      - .variables.env
    depends_on:
      - mongo

volumes:
  mongo-data:
