name: Deploy MERN App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app (if needed)
        run: npm run build || echo "No build step defined"

      - name: Ensure .env exists
        run: |
          if [ ! -f .env ]; then
            echo "Creating default .env file..."
            cat <<EOT >> .env
MONGO_URI=your_mongo_uri_here
SESSION_SECRET=your_session_secret_here
PORT=8086
EOT
          else
            echo ".env file exists"
          fi

      - name: Load environment variables from .env
        run: export $(grep -v '^#' .env | xargs)

      - name: Install PM2
        run: npm install -g pm2

      - name: Start/Restart app with PM2
        run: |
          pm2 describe mern-admin || pm2 start npm --name "mern-admin" -- start
          pm2 restart mern-admin
          pm2 save
