name: Node.js CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build (if you have a build step)
      - name: Build
        run: npm run build || echo "No build step defined"

      # Step 5: Start the app (optional: only if you want to run it)
      - name: Start app
        run: |
          echo "Starting app..."
          nohup npm start &

      # Step 6: Confirm deployment (optional)
      - name: Check app running
        run: |
          sleep 5
          curl -s http://localhost:8080 || echo "App not accessible yet"
