name: Deploy MERN Admin

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cleanup old containers
        run: |
          echo "Removing old containers if they exist..."
          docker rm -f mern-admin || true
          docker rm -f mongo || true

      - name: Deploy with Docker Compose
        run: |
          DATABASE=mongodb://mongo:27017/mydb \
          SECRET=mySuperSecret \
          KEY=mySessionKey \
          docker compose down -v

          DATABASE=mongodb://mongo:27017/mydb \
          SECRET=mySuperSecret \
          KEY=mySessionKey \
          docker compose up --build -d

      - name: Show logs (first 20 lines)
        run: |
          docker logs mern-admin --tail 20
