name: Deploy MERN Admin

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy on Self-Hosted Runner
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Remove old containers if they exist
        run: |
          docker rm -f mern-admin || true
          docker rm -f mongo || true
          docker volume rm mern-admin_mongo-data || true

      - name: Build and run containers
        run: |
          docker compose up --build -d

      - name: Wait for app to start
        run: |
          echo "Waiting 10 seconds for app to start..."
          sleep 10

      - name: Test server
        run: |
          curl -f http://localhost:8192/test
