name: Deploy MERN Admin

on:
  push:
    branches:
      - master   # or master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove old containers
        run: |
          echo "Cleaning up old containers..."
          docker rm -f mern-admin || true
          docker rm -f mongo || true

      - name: Deploy with Docker Compose
        run: |
          docker compose -f docker-compose.yml down
          docker compose -f docker-compose.yml up -d --build
