name: Deploy MERN Admin

on:
  push:
    branches:
      - master  # deploy on pushes to main branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cleanup old containers
        run: |
          echo "Removing old containers if they exist..."
          docker rm -f mern-admin || true
          docker rm -f mongo || true

      - name: Deploy with Docker Compose
        run: |
          docker compose --env-file .variables.env down -v
          docker compose --env-file .variables.env up --build -d

      - name: Show logs (first 20 lines)
        run: |
          docker logs mern-admin --tail 20
